const minimatch = require('minimatch')
const match = require('./lib/rbac')._match
console.log(minimatch('blog', 'blog'))
console.log(minimatch('blog', '*'))
console.log(minimatch('/user/123/blog', '*'))
console.log(minimatch('/user/123/blog', '**'))
console.log(minimatch('*', '*'))
console.log(minimatch('*', 'blog'))
console.log(minimatch('/user/123/blog', '/user/**'))
console.log(minimatch('/user/123/blog', 'blog'))

console.log('------------------rbac test-------------------------')
console.log(match('/user/123/blog:post', '/user/**:post'))
console.log(match('blog:post', 'blog:*'))
console.log(match('blog:post', '*:*'))
console.log(match('blog:post', '*:post'))
console.log(match('blog:post:put', '*:post'))